import Message from "../components/Message";
import { useEffect, useState } from "react";
import { db } from "../utils/firebase";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
	const [allPosts, setAllPosts] = useState([]);

	const getPosts = async () => {
		const collectionRef = collection(db, "posts");
		const q = query(collectionRef, orderBy("timestamp", "desc"));
		const unsubscribe = onSnapshot(q, (snapshot) => {
			setAllPosts(
				snapshot.docs.map((doc) => ({
					...doc.data(),
					id: doc.id,
				}))
			);
		});
		return unsubscribe;
	};

	useEffect(() => {
		getPosts();
	}, []);

	return (
		<>
			<Head>
				<title>Fasebook</title>
				<meta
					name="decription"
					content="Generated by Next"
				/>
			</Head>
			<div className="my-8 text-g font-medium">
				<h2>See what other people are saying</h2>
				{allPosts.map((post) => (
					<Message key={post.id} {...post}>
						<Link
							href={{
								pathname: `/${post.id}`,
								query: {
									...post,
								},
							}}
						>
							<button className="text-sm text-gray-700 hover:text-gray-500">
								{post.comments
									?.length >
								0
									? post
											.comments
											?.length
									: 0}{" "}
								Comments
							</button>
						</Link>
					</Message>
				))}
			</div>
		</>
	);
}
